version: '3.8'
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file: 
      - .env

networks:
  default:
    external:
      name: shared
