name: auto-deploy
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install node.js 
        run: |
          curl -o- https://fnm.vercel.app/install | bash
          fnm install 22
          node -v
          npm -v
  
      - name: Install npm packages
        run: |
          npm install
  
      - name: Build
        run: |
          npm run build

      - name: Connect to vps with ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd ${{ secrets.SSH_PROJECT_PATH }}

            # Create `.env`
            echo "VIRTUAL_PROTO=${{ secrets.VIRTUAL_PROTO }}" > .env
            echo "VIRTUAL_PORT=${{ secrets.VIRTUAL_PORT }}" >> .env
            echo "VIRTUAL_HOST=${{ secrets.VIRTUAL_HOST }}" >> .env
            echo "LETSENCRYPT_HOST=${{ secrets.VIRTUAL_HOST }}" >> .env
            echo "LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}" >> .env
            
            # Deploy
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
